.PHONY: clean All

All:
	@echo "----------Building project:[ ktcl - Debug ]----------"
	@cd "C:\Users\sebastien\Documents\dev\tcl\ktcl" && $(MAKE) -f  "ktcl.mk"
clean:
	@echo "----------Cleaning project:[ ktcl - Debug ]----------"
	@cd "C:\Users\sebastien\Documents\dev\tcl\ktcl" && $(MAKE) -f  "ktcl.mk" clean
