.PHONY: clean All

All:
	@echo "----------Building project:[ ktcl - Debug ]----------"
	@cd "F:\work\ktcl" && $(MAKE) -f  "ktcl.mk"
clean:
	@echo "----------Cleaning project:[ ktcl - Debug ]----------"
	@cd "F:\work\ktcl" && $(MAKE) -f  "ktcl.mk" clean
